### ISSUE TITLE
run_inline_query

### ISSUE THREAD

**Issue by markebrown** [looker/lookr#5]
I am getting this error trying to run run_inline_query. I got run_look to work. Did something change with run_inline_query or am I doing something wrong? Thanks.

my_inline_query <- run_inline_query(model = "shipments", 
                                     view = "accounts", 
                                    fields = c("accounts.count"))
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  io.swagger.client.ApiException: {"message":"Not found","documentation_url":"http://docs.looker.com/"}

**Comment by githoov** [comment]
@markebrown I'm seeing this as well. I'll do some research.

**Comment by thekenz** [comment]
I checked around here, and found that this is actually caused by when `view:` is referencing a view that isn't listed as the base view for an Explore. 

So let's say that I have this model file:

```
- connection: thelook

- include: "*.view.lookml"       # include all the views
- include: "*.dashboard.lookml"  # include all the dashboards


- explore: order_items
  joins:
    - join: inventory_items
      type: left_outer
      sql_on: ${order_items.inventory_item_id} = ${inventory_items.id}
      relationship: many_to_one

    - join: orders
      type: left_outer
      sql_on: ${order_items.order_id} = ${orders.id}
      relationship: many_to_one

    - join: products
      type: left_outer
      sql_on: ${inventory_items.product_id} = ${products.id}
      relationship: many_to_one

    - join: users
      type: left_outer
      sql_on: ${orders.user_id} = ${users.id}
      relationship: many_to_one
      
    - join: users_orders_facts
      type: left_outer
      relationship: many_to_one
      sql_on: ${users.id} = ${users_orders_facts.user_id}
```
As it stands, I can only set `view` in the `run_inline_query` command here to be equal to `order_items` and nothing else, because the only view declared in the model file is `order_items`. 

In other words, this will work:

```
my_inline_query <- run_inline_query(model = "the_look", 
                                    view = "order_items", 
                                    fields = c("orders.count", "orders.created_month"))
```
This will not work:

```
my_inline_query <- run_inline_query(model = "the_look", 
                                    view = "orders", 
                                    fields = c("orders.count", "orders.created_month"))
```

You'll need to declare orders as an Explore for this to work. As it stands, its probably more apropos to call this `explore`, rather than `view`.
